from queue import Queue
q=Queue(maxsize=4)
print(q.qsize())
q.put(10)
q.put(20)
q.put(30)
print("\nFull",q.full())
print(q.get())
print(q.get())
print(q.get())
print("\nEmpty:",q.empty())
q.put(7)
print(q.get())
print("\nEmpty:",q.empty())